### ISSUE TITLE
calling SetApiVersion before authentication gives permissions error

### ISSUE THREAD

**Issue by XertroV** [EvoEsports/GbxRemote.Net#88]
using the example script:

```
Unhandled exception. GbxRemoteNet.Exceptions.XmlRpcFaultException: (-1000) Permission denied.
   at GbxRemoteNet.GbxRemoteClient.CallOrFaultAsync(String method, Object[] args)
   at GbxRemoteNet.GbxRemoteClient.SetApiVersionAsync(String version)
   at GbxRemoteNet.GbxRemoteClient.LoginAsync(String login, String password)
   at Program.<Main>$(String[] args)
```

**Comment by XertroV** [comment]
this is a problem because AFAIK you can't choose to send SetApiVersion after authenticating

**Comment by snixtho** [comment]
I'm unable to reproduce this error, what server version are you running?

**Comment by XertroV** [comment]
Was the latest (2024-03-18 from memory, just via evo docker image)
On a linux server
