### ISSUE TITLE
exception getting server config

### ISSUE THREAD

**Issue by XertroV** [EvoEsports/GbxRemote.Net#91]
When I try to get my server config I get this exception:
```
Unhandled exception: System.ArgumentException: Object of type 'System.Int32' cannot be converted to type 'System.Nullable`1[System.Boolean]'.
   at System.RuntimeType.CheckValue(Object& value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at GbxRemoteNet.XmlRpc.XmlRpcTypes.ToNativeStruct[T](XmlRpcStruct xmlStruct, Type instanceType)
   at GbxRemoteNet.XmlRpc.XmlRpcTypes.ToNativeValue[T](XmlRpcBaseType xmlValue, Type instanceType)
   at GbxRemoteNet.GbxRemoteClient.GetServerOptionsAsync()
```

Not sure why, will update if i find out

**Comment by XertroV** [comment]
I also get this exception when creating new options and trying to set server options.

```
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GbxRemoteNet.XmlRpc.Types.XmlRpcStruct.GetXml()
   at GbxRemoteNet.XmlRpc.XmlRpcCall..ctor(String method, XmlRpcBaseType[] args)
   at GbxRemoteNet.XmlRpc.Packets.MethodCall..ctor(String method, UInt32 handle, XmlRpcBaseType[] args)
   at GbxRemoteNet.XmlRpc.NadeoXmlRpcClient.CallAsync(String method, XmlRpcBaseType[] args)
   at GbxRemoteNet.GbxRemoteClient.CallOrFaultAsync(String method, Object[] args)
   at GbxRemoteNet.GbxRemoteClient.SetServerOptionsAsync(TmServerOptions options)
```

**Comment by AtomicLiquid** [comment]
@snixtho any ideas?

**Comment by XertroV** [comment]
config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<dedicated>
        <authorization_levels>
                <level>
                        <name>SuperAdmin</name>
                        <password>{{SUPER_ADMIN_PW}}</password>
                </level>
                <level>
                        <name>Admin</name>
                        <password>{{ADMIN_PW}}</password>
                </level>
                <level>
                        <name>User</name>
                        <password>{{USER_PW}}</password>
                </level>
        </authorization_levels>

        <masterserver_account>
                <login>{{DEDI_USERNAME}}</login>
                <password>{{DEDI_PASSWORD}}</password>
        </masterserver_account>

        <server_options>
                <name>{{SERVER_NAME}}</name>
                <comment/>
                <!-- value is 0 (always shown), 1 (always hidden), 2 (hidden from nations) -->
                <!-- <hide_server>0</hide_server>                                     -->

                <!-- ARBITRARY, ANYONE ON GUEST LIST CAN JOIN -->
                <!-- NOTE: THE CONTROLLER WILL WATCH FOR NON WHITELISTED PLAYERS -->
                <max_players>100</max_players>
                <password/>

                <max_spectators>100</max_spectators>
                <password_spectator/>

                <keep_player_slots>False</keep_player_slots>                    <!-- when a player changes to spectator, hould the server keep if player slots/scores etc.. or not. -->
                <ladder_mode>forced</ladder_mode>                               <!-- value between 'inactive', 'forced' (or '0', '1') -->

                <enable_p2p_upload>True</enable_p2p_upload>
                <enable_p2p_download>False</enable_p2p_download>

                <callvote_timeout>1000</callvote_timeout>

                <!-- NO VOTING -->
                <callvote_ratio>1.0</callvote_ratio>                            <!-- default ratio. value in [0..1], or -1 to forbid. -->
                <callvote_ratios>
                        <voteratio command="Ban" ratio="-1"/>
                        <voteratio command="Kick" ratio="-1"/>
                        <voteratio command="RestartMap" ratio="-1"/>
                        <voteratio command="NextMap" ratio="-1"/>
                        <voteratio command="SetModeScriptSettingsAndCommands" ratio="-1"/>
                        <!-- commands can be "Ban", "Kick", "RestartMap", "NextMap", "SetModeScriptSettingsAndCommands"... -->
                </callvote_ratios>

                <allow_map_download>False</allow_map_download>
                <autosave_replays>False</autosave_replays>
                <autosave_validation_replays>False</autosave_validation_replays>

                <referee_password/>
                <!-- value is 0 (only validate top3 players),  1 (validate all players) -->
                <!-- <referee_validation_mode>0</referee_validation_mode>            -->

                <use_changing_validation_seed>False</use_changing_validation_seed>

                <disable_horns>True</disable_horns>
                <!-- ignore player chosen skins and only use default country skin -->
                <disable_profile_skins>False</disable_profile_skins>
                <!-- <disable_profile_skins>True</disable_profile_skins> -->


                <!-- IS THIS COMMENT ACCURATE? WHAT'S THE EFFECT ON US PPL? (OR AUS, ETC) -->
                <clientinputs_maxlatency>375</clientinputs_maxlatency>      <!-- players with c2s-latency greater than this value will experience difficulties playing, but a lower value reduce overall clients CPU usage (max 540ms) -->
        </server_options>

        <system_config>
                <!-- CAN THIS BE TOO HIGH? -->
                <connection_uploadrate>10002400</connection_uploadrate>                                           <!-- Kbits per second -->
                <connection_downloadrate>10002400</connection_downloadrate>                                       <!-- Kbits per second -->

                <!-- SERVER HAS ONLY 2 VCPUS -->
                <workerthreadcount>2</workerthreadcount>
                <packetassembly_multithread>True</packetassembly_multithread>
                <packetassembly_packetsperframe>60</packetassembly_packetsperframe>                 <!-- Number of reduced SIMU-packets sent each frame (=10ms) -->
                <packetassembly_fullpacketsperframe>30</packetassembly_fullpacketsperframe>         <!-- Number of full SIMU-packets sent each frame (=10ms) -->

                <!-- CAN WE GO HIGHER? -->
                <delayedvisuals_s2c_sendingrate>64</delayedvisuals_s2c_sendingrate>                 <!-- proportion of frames when the server sends DELAYEDVISUAL-packets to everyone. 255 means every frame, 128 means every other frame, 64 means every fourth frame... -->

                <!-- CAN WE GO HIGHER? -->
                <trustclientsimu_c2s_sendingrate>64</trustclientsimu_c2s_sendingrate>               <!-- proportion of frames when the clients send TRUSTCLIENTSIMU-packets to the server.  255 means every frame, 128 means every other frame, 64 means every fourth frame... -->

                <allow_spectator_relays>False</allow_spectator_relays>

                <p2p_cache_size>600</p2p_cache_size>

                <force_ip_address></force_ip_address>
                <server_port>2350</server_port>
                <client_port>0</client_port>
                <bind_ip_address/>
                <use_nat_upnp/>

                <gsp_name/>                                             <!-- Game Server Provider name and info url -->
                <gsp_url/>                                              <!-- If you're a server hoster, you can use this to advertise your services -->

                <xmlrpc_port>5000</xmlrpc_port>
                <xmlrpc_allowremote>True</xmlrpc_allowremote>                  <!-- If you specify an ip adress here, it'll be the only accepted adress. this will improve security. -->


                <blacklist_url/>
                <guestlist_filename>guestlist.txt</guestlist_filename>
                <blacklist_filename/>

                <minimum_client_build/>                 <!-- Only accept updated client to a specific version. ex: 2011-10-06 -->

                <!-- WILL DISABLING THIS HELP -->
                <disable_coherence_checks>False</disable_coherence_checks>      <!-- disable internal checks to detect issues/cheats, and reject race times -->

                <disable_replay_recording>True</disable_replay_recording>      <!-- disable replay recording in memory during the game to lower memory usage. -->
                <save_all_individual_runs>False</save_all_individual_runs>      <!-- Save all the ghosts from the match replay to individual ghost.gbx files, in folder {servername}/Autosaves/Runs_{mapname}/  -->

                <use_proxy>False</use_proxy>
                <proxy_url/>
        </system_config>
</dedicated>
```

**Comment by Chris92de** [comment]
Found the part where it's crashing.
[`HideServer` in TmServerOptions.cs](https://github.com/EvoEsports/GbxRemote.Net/blob/78e088fcc9717fea4cdd427a1eda5a81a642b7ca/src/GbxRemote.Net/Structs/TmServerOptions.cs#L19) is defined as nullable bool, however the server sends an Int32 value of 0.
